version: "3.9"
services:
  mysql:
    ports:
      - "3306:3306"
    build: 
      dockerfile: docker/mysql.Dockerfile
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbData:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8090:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
  php-apache:
    ports:
      - "80:80"
    build: 
      dockerfile: docker/php.Dockerfile
    volumes:
      - .:/var/www/html/
    env_file:
      - .env
    depends_on:
      - mysql
      - phpmyadmin
  
volumes:
  dbData: