version: "3.9"
services:
  php-apache:
    ports:
      - "80:80"
    build: 
      dockerfile: php.Dockerfile
    volumes:
      - .:/var/www/html/
  mysql:
    ports:
      - "3306:3306"
    build: 
      dockerfile: mysql.Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "orm_nose42_intra"
    volumes:
      - dbData:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8090:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: "root"
volumes:
  dbData: