version: "3.9"
services:
  php-apache:
    ports:
      - "80:80"
    build: 
      dockerfile: php.Dockerfile
    volumes:
      - .:/var/www/html/
      - /var/www/html/vendor
    env_file:
      - .env
  mysql:
    ports:
      - "3306:3306"
    build: 
      dockerfile: mysql.Dockerfile
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbData:/var/lib/mysql
    container_name: ${DB_HOST}
  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8090:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
volumes:
  dbData: