name: Release to production

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          tools: composer:v2

      - name: Composer install
        run: composer install --prefer-dist --no-progress --no-suggest --no-dev --optimize-autoloader

      - name: Enable https
        run: sed -i 's/#https //g' .htaccess

      - name: Deploy with rsync
        uses: burnett01/rsync-deployments@5.2.2
        with:
          switches: -avz --filter=". .rsync-filter" --delete-after
          path: ./
          remote_path: ./
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_key: ${{ secrets.DEPLOY_SSH_KEY }}
          remote_key_pass: ${{ secrets.DEPLOY_SSH_KEY_PASS }}

      - name: Apply migrations and generate proxies
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          passphrase: ${{ secrets.DEPLOY_SSH_KEY_PASS }}
          script: |
            php bin/doctrine migrations:migrate
            php bin/doctrine orm:generate-proxies
