name: Staging release - Intranose

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          tools: composer:v2

      - name: Composer install
        run: composer install --prefer-dist --no-progress --no-suggest --no-dev --optimize-autoloader

      - name: Enable https
        run: sed -i 's/#https //g' .htaccess

      - name: Deploy with rsync
        uses: burnett01/rsync-deployments@5.2.2
        with:
          switches: -avz --filter=". .rsync-filter" --delete-after
          path: ./
          remote_path: ./
          remote_host: ${{ secrets.STAGING_DEPLOY_HOST }}
          remote_user: ${{ secrets.STAGING_DEPLOY_USER }}
          remote_key: ${{ secrets.STAGING_DEPLOY_SSH_KEY }}
          remote_key_pass: ${{ secrets.STAGING_DEPLOY_SSH_KEY_PASS }}

      - name: Migration hook
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.HOOK_MIGRATION_URL_INTRA_STAGING }}
          method: "GET"
