name: PHPUnit Tests

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  test:
    name: Run PHPUnit Tests
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_DATABASE: test_database
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          tools: composer:v2

      - name: Composer install
        run: composer install --prefer-dist --no-progress --no-suggest --dev --optimize-autoloader

      - name: Generate .env
        run: |
          echo "DB_USER=test_user" > .env
          echo "DB_PASSWORD=test_password" >> .env
          echo "DB_HOST=localhost" >> .env
          echo "DB_PORT=3306" >> .env
          echo "TEST_DB_NAME=test_database" >> .env
          echo "DB_NAME=test_database" >> .env

      - name: Run PHPUnit
        run: php bin/phpunit
