name: Test

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  test:
    name: phpunit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          tools: composer:v2

      - name: Composer install
        run: composer install --prefer-dist --no-progress --no-suggest --dev --optimize-autoloader

      - name: Generate .env
        run: |
          echo "DEVELOPMENT=true" > .env

      - name: Run PHPUnit
        run: php bin/phpunit
